import { Movie } from './store';

export const MOCK_MOVIES: Movie[] = [
  {
    id: 1,
    title: "Stranger Things",
    description: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    duration: "50m",
    genre: ["Sci-Fi", "Horror", "Drama"],
    match: 98,
    year: 2022,
    rating: "TV-14",
    isTop10: 1,
    media_type: 'tv',
  },
  {
    id: 2,
    title: "The Witcher",
    description: "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/cJrLt0y5d3QX11B6rA5w4I4a44i.jpg",
    duration: "1h",
    genre: ["Fantasy", "Action"],
    match: 95,
    year: 2023,
    rating: "TV-MA",
    isTop10: 2,
    media_type: 'tv',
  },
  {
    id: 3,
    title: "Wednesday",
    description: "Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends — and foes — at Nevermore Academy.",
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    duration: "45m",
    genre: ["Comedy", "Fantasy"],
    match: 97,
    year: 2022,
    rating: "TV-14",
    isTop10: 3,
    media_type: 'tv',
  },
  {
    id: 4,
    title: "Black Mirror",
    description: "Sci-fi anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide.",
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/7brj1W87F7825YnJ7a9F8r7d9.jpg",
    duration: "1h",
    genre: ["Sci-Fi", "Drama", "Thriller"],
    match: 90,
    year: 2023,
    rating: "TV-MA",
    isTop10: 4,
    media_type: 'tv',
  },
  {
    id: 5,
    title: "Breaking Bad",
    description: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pWU4uYj2c6I2.jpg",
    duration: "48m",
    genre: ["Crime", "Drama"],
    match: 99,
    year: 2013,
    rating: "TV-MA",
    isTop10: 0,
    media_type: 'tv',
  },
  {
    id: 6,
    title: "Squid Game",
    description: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes.",
    thumbnailUrl: "https://image.tmdb.org/t/p/w500/dDlE2FcFEytjcFYgISQd6aW3a4.jpg",
    duration: "55m",
    genre: ["Thriller", "Drama"],
    match: 96,
    year: 2021,
    rating: "TV-MA",
    isTop10: 0,
    media_type: 'tv',
  }
];